In [1]:
import numpy as np

In [3]:
x1 = np.array([[1, 2],
              [3, 4],
              [5, 6]])
print(x1.shape)

(3, 2)


In [7]:
x2 = np.array([[7, 7, 7]])
print(x2.shape)
print(x2.T.shape)

(1, 3)
(3, 1)


In [9]:
X = np.concatenate((x1, x2.T), axis=1)
print(X)
print(X.shape)

[[1 2 7]
 [3 4 7]
 [5 6 7]]
(3, 3)


In [11]:
X = np.column_stack((x1, x2.T))
print(X)
print(X.shape)

[[1 2 7]
 [3 4 7]
 [5 6 7]]
(3, 3)
